set character_set_server='utf8';
SET FOREIGN_KEY_CHECKS = 0;
delete from iptv.dsmtv_movie;
INSERT into iptv.dsmtv_movie(id, name, api, state) select '1','影视仓','http://影视仓.com','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '10','小米','http://xhww.fun:63/小米/DEMO.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '11','巧技','http://cdn.qiaoji8.com/tvbox.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '12','香雅情','https://wget.la/https://raw.githubusercontent.com/xyq254245/xyqonlinerule/main/XYQTVBox.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '13','讴歌','http://tv.nxog.top/m','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '14','Fongmi','https://raw.githubusercontent.com/gaotianliuyun/fongmi/main/json/config.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '15','俊于','http://home.jundie.top:81/top98.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '16','霜辉月明py','https://wget.la/raw.githubusercontent.com/lm317379829/PyramidStore/pyramid/py.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '17','运输车','https://wget.la/https://raw.githubusercontent.com/52670576/tvbox/main/ysc.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '18','巧技','http://pandown.pro/tvbox/tvbox.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '19','胖虎','https://notabug.org/imbig66/tv-spider-man/raw/master/配置/0801.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '2','摸鱼','http://我不是.摸鱼儿.com','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '20','Ray','https://wget.la/https://raw.githubusercontent.com/dxawi/0/main/0.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '21','OK影视','https://jsdelivr.pai233.top/gh/2hacc/TVBox@main/oktv.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '22','摸鱼2','http://我不是.摸鱼儿.top','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '23','霜辉月明py','https://wget.la/raw.githubusercontent.com/lm317379829/PyramidStore/pyramid/py.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '24','qist_tvbox','https://wget.la/raw.githubusercontent.com/qist/tvbox/master/jsm.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '25','采集之王','https://wget.la/https://raw.githubusercontent.com/jiushizhe/daozhang/main/drpy_dzlive6.21/index.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '26','开心软件','https://wget.la/https://raw.githubusercontent.com/ls125781003/tvboxtg/main/天天开心/api.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '27','高天','https://wget.la/raw.githubusercontent.com/gaotianliuyun/gao/master/js.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '28','刘备','https://raw.liucn.cc/box/m.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '29','心魔线路','https://jihulab.com/yw88075/tvbox/-/raw/main/dr/js.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '3','OK线路','http://ok321.top/tv','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '4','kstore','https://12586.kstore.space/123.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '5','盒子迷','https://盒子迷.top/春盈天下','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '6','pandown','http://pandown.pro/tvbox/tvbox.json','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '7','刺猬','https://www.cwss.xyz/刺猬线路禁止贩卖','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '8','肥猫','http://肥猫.com','1';
INSERT into iptv.dsmtv_movie(id, name, api, state) select '9','饭太硬','http://fty.xxooo.cf/tv','1';
SET FOREIGN_KEY_CHECKS = 1;
commit;
