name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: '01 16 * * *'
  push:
    branches: [ "Files" ]

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

    - name: Update
      run: |
        chmod +x iptv_to_sql.sh;
        bash -vvv ./iptv_to_sql.sh

    - name: Clean
      run: |
        echo "Auto Update IPTV at ${{ steps.date.outputs.date }}" > README.md
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"


    - name: Push
      run: git push -f origin Files
