name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: '01 16 * * *'


env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

    - name: Update
      run: |
        chmod -R 755 scripts/*;
        bash -vvv scripts/iptv_to_sql.sh
        bash -vvv scripts/duocang_sql.sh
        ###########################################################
        # echo "# 所有数据来源于互联网，内容真实性请用户自行辨认。" > README.md
        # echo '' >> README.md
        # echo "# 本源码仅供学习，禁止用于违法犯罪行为，否则后果自负！" >> README.md
        # echo '' >> README.md
        sed -i "s/# Auto Update IPTV at.*/# Auto Update IPTV at ${{ steps.date.outputs.date }}/g"  README.md
        # echo '----------------------------------------------------' >> README.md

    - name: Clean
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"


    - name: Push
      run: git push -f origin Files
